/*
 *
 * Signal constants
 *
 */

export const DEFAULT_ACTION = 'app/Signal/DEFAULT_ACTION';
export const GET_PENDING_SIGNALS = 'app/Signal/GET_PENDING_SIGNALS';
export const GET_PENDING_SIGNALS_PENDING = 'app/Signal/GET_PENDING_SIGNALS_PENDING';
export const GET_PENDING_SIGNALS_SUCCESS = 'app/Signal/GET_PENDING_SIGNALS_SUCCESS';
export const GET_PENDING_SIGNALS_FAILED = 'app/Signal/GET_PENDING_SIGNALS_FAILED';
