/*
 *
 * SignupForm constants
 *
 */

export const SIGNUP = 'SIGNUP/SIGNUP';
export const PRE_SIGNUP = 'SIGNUP/PRE_SIGNUP';
export const SIGNUP_PENDING = 'SIGNUP/SIGNUP_PENDING';
export const SIGNUP_PRE_SUCCESS = 'SIGNUP/SIGNUP_PRE_SUCCESS';
export const SIGNUP_PRE_FAILURE = 'SIGNUP/SIGNUP_PRE_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP/SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP/SIGNUP_FAILURE';
export const SIGNUP_CHANGE_EMAIL = 'SIGNUP/CHANGE_EMAIL';
export const SIGNUP_CHANGE_FORM = 'SIGNUP/CHANGE_FORM';
