/*
 *
 * LoginForm constants
 *
 */
export const LOGIN = 'LOGIN/LOGIN';
export const LOGIN_PENDING = 'LOGIN/LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN/LOGIN_FAILURE';
export const LOGIN_CHANGE_EMAIL = 'LOGIN/CHANGE_EMAIL';
export const LOGIN_CHANGE_PASSWORD = 'LOGIN/CHANGE_PASSWORD';
